REQUIRED_COLUMNS = [
    "Название",
    "Цена",
    "Описание",
    "Дата публикации",
    "URL",
]

OPTIONAL_OUTPUT_COLUMNS = [
    "Цвет",
    "Гарантия",
]

PREVIEW_ROWS_COUNT = 5
EXTRACTION_PREVIEW_ROWS_COUNT = 20

COMMON_BRANDS = [
    "apple",
    "samsung",
    "huawei",
    "xiaomi",
    "oppo",
    "garmin",
    "amazfit",
    "honor",
    "google",
    "oneplus",
    "realme",
    "suunto",
    "ticwatch",
]

COLOR_MAP = {
    "black": "Black",
    "white": "White",
    "silver": "Silver",
    "gray": "Gray",
    "grey": "Grey",
    "gold": "Gold",
    "pink": "Pink",
    "purple": "Purple",
    "blue": "Blue",
    "green": "Green",
    "red": "Red",
    "orange": "Orange",
    "yellow": "Yellow",
    "biege": "Beige",
    "brown": "Brown",
    "beige": "Beige",
    "rose": "Rose Gold",
    "rose gold": "Rose Gold",
    "light blush": "Pink",

    "черный": "Black",
    "чёрный": "Black",
    "белый": "White",
    "серебристый": "Silver",
    "серый": "Gray",
    "серый": "Grey",
    "золотой": "Gold",
    "розовый": "Pink",
    "фиолетовый": "Purple",
    "синий": "Blue",
    "голубой": "Blue",
    "зеленый": "Green",
    "зелёный": "Green",
    "красный": "Red",
    "оранжевый": "Orange",
    "желтый": "Yellow",
    "жёлтый": "Yellow",
    "бежевый": "Biege",
    "коричневый": "Brown",

    "белые": "White",
    "белая": "White",
    "белое": "White",
    "черные": "Black",
    "чёрные": "Black",
    "черная": "Black",
    "чёрная": "Black",
    "серые": "Gray",
    "серебристые": "Silver",
    "золотые": "Gold",
    "фиолетовые": "Purple",
    "розовые": "Pink",
    "синие": "Blue",
    "зеленые": "Green",
    "зелёные": "Green",
    "красные": "Red",
    "бежевые": "Beige",
}

MODEL_NOISE_TOKENS = {
    "mm",
    "lte",
    "wifi",
    "gps",
    "nfc",
    "sport",
    "band",
    "strap",
    "fog",
    "space",
    "light",
    "blush",
    "titanium",
    "s",
    "m",
    "l",
    "xl",
    "sm",
    "ml",
    "rose",
    "gold",
    "beige",
    "purple",
    "gray",
    "grey",
    "black",
    "white",
    "silver",
    "pink",
    "blue",
    "green",
    "red",
    "orange",
    "yellow",
    "4g",
    "детские",
    "умные",
    "часы",
    "смарт",
    "smart",
}